#!/bin/bash

echo "Create a factlet named '$1' containing '$2'?"
read -r -p "Are you sure? [y/N] " response
if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]
then
#    echo "said yes"
	DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
    source $DIR/config
    name="${1// /_}"
    now="$(date +'%m_%d_%Y')"
    #echo $now
    {
    	mkdir $DIR/$factlet_dir/$now/
	} &> /dev/null
    printf "#  Today I learned about: $1 \n \n$2 \n \n...and now, you've learned that too!\n" > $DIR/$factlet_dir/$now/$name.md
    git add $DIR/$factlet_dir/$now/$name.md
    git commit -m "new factlet for $now"
    git push origin 
else
    echo "O.K.; keep thinking!"
fi